# Generated by Django 6.0.3 on 2026-03-25 21:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('weight_in_stock', models.DecimalField(decimal_places=2, help_text='Current weight in KGs', max_digits=10)),
                ('buying_price', models.DecimalField(decimal_places=2, help_text='Price bought per KG', max_digits=10)),
                ('selling_price', models.DecimalField(decimal_places=2, help_text='Price sold per KG', max_digits=10)),
                ('min_stock_level', models.DecimalField(decimal_places=2, default=10.0, help_text='Alert when stock hits this weight', max_digits=10)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.category')),
            ],
        ),
    ]
