# Generated by Django 6.0.3 on 2026-03-31 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_sale'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sale',
            old_name='timestamp',
            new_name='created_at',
        ),
    ]
